# Generated by Django 2.2.9 on 2021-02-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('Maritalstatus', models.CharField(max_length=255)),
                ('Occupation', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('hours_per_week', models.CharField(max_length=255)),
                ('native_country', models.CharField(max_length=255)),
                ('houseInfo', models.CharField(max_length=255)),
                ('monthySalary', models.CharField(max_length=255)),
                ('OtherMonthlyIncome', models.CharField(max_length=255)),
                ('SavingBalance', models.CharField(max_length=255)),
                ('Investment', models.CharField(max_length=255)),
                ('Property', models.CharField(max_length=255)),
                ('CreditCardLiabilities', models.CharField(max_length=255)),
                ('HomeMortgage', models.CharField(max_length=255)),
                ('OtherLoan', models.CharField(max_length=255)),
                ('Foodspend', models.CharField(max_length=255)),
                ('clothingspend', models.CharField(max_length=255)),
                ('shopping', models.CharField(max_length=255)),
                ('accommodation', models.CharField(max_length=255)),
                ('Transport', models.CharField(max_length=255)),
                ('othersMonthlyspend', models.CharField(max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
        ),
    ]
